eShopLab/Controllers/CatlgController.cs
using eShopLab.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using Newtonsoft.Json;

namespace eShopLab.Controllers
{
    public class CatlgController : Controller
    {
        private eShopDBEntities db = new eShopDBEntities();

        //
        // GET: /Catlg/

        public ActionResult Index(int? categoryID, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.categoryID = categoryID;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            ViewBag.Categories = db.Categories.Where(c => c.CategoryIsMenu == true);

            IEnumerable<Product> products;
            if (categoryID != null)
            {
                products = db.Products.Where(p => p.CategoryID == categoryID);
            }
            else
            {
                products = db.Products;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.ProductName.ToUpper().Contains(searchString.ToUpper())
                                       || s.ProductDescription.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "Name_desc":
                    products = products.OrderByDescending(s => s.ProductName);
                    break;
                case "Price_asc":
                    products = products.OrderBy(p => p.LastPrice);
                    break;
                case "Price_desc":
                    products = products.OrderByDescending(p => p.LastPrice);
                    break;
                default:
                    products = products.OrderBy(s => s.ProductName);
                    break;
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(products.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(int id)
        {
            List<string> size = db.Products.Find(id).ProductSizeCategories.Select(s => s.SizeCategory.SizeCategoryInitial).ToList();

            SizeC sizeC = new SizeC()
            {
                SizeCategoryList = size,
                choice = size.FirstOrDefault()
            };

            string json = JsonConvert.SerializeObject(sizeC, Formatting.Indented);

            ViewBag.SizeCategoryJson = json;

            ViewBag.product = db.Products.Find(id);
            return View();
        }
    }
}

eShopLab/Views/Catlg/Details.cshtml
@model eShopLab.Models.Product
@using eShopLab.Helper;
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-12">

        <!-- Best Seller -->
        <div class="col-lg-12 col-md-12 col-sm-12 visible-lg visible-md">
            <div class="no-padding">
                <span class="title">BEST SELLER</span>
            </div>
            <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
                <a href="detail.html" class="link-p">
                    <img src="~/images/product-8.jpg" alt="">
                </a>
                <div class="caption prod-caption">
                    <h4><a href="detail.html">Penn State College T-Shirt</a></h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
                    <p>
                        <div class="btn-group">
                            <a href="#" class="btn btn-default">$ 528.96</a>
                            <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                        </div>
                    </p>
                </div>
            </div>
            <div class="thumbnail col-lg-12 col-md-12 col-sm-6 hidden-xs text-center">
                <a href="detail.html" class="link-p">
                    <img src="~/images/product-9.jpg" alt="">
                </a>
                <div class="caption prod-caption">
                    <h4><a href="detail.html">Ohio State College T-Shirt</a></h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
                    <p>
                        <div class="btn-group">
                            <a href="#" class="btn btn-default">$ 924.25</a>
                            <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                        </div>
                    </p>
                </div>
            </div>
        </div>
        <!-- End Best Seller -->

    </div>

    <div class="clearfix visible-sm"></div>

    <!-- Product Detail -->
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <span class="title">@ViewBag.product.ProductName</span>
        </div>
        <div class="col-lg-12 col-sm-12 hero-feature">
            <div class="sp-wrap">
                @foreach (var media in ((eShopLab.Models.Product)@ViewBag.product).Media.Take(5))
                {
                    <a href="@Url.Content(media.MediaUrl)"><img class="smoothimg prod-detail" src="@Url.Content(media.MediaUrl)" alt=""></a>
                }
            </div>
            <h4>@ViewBag.product.ProductDescription</h4>
            @ViewBag.product.TotalQuantity items in stock
            <hr />
            @ViewBag.product.ProductLongDescription
            <hr />
            <h3>@String.Format("{0:C}", ((eShopLab.Models.Product)ViewBag.product).Prices.Where(p => p.PriceDate == ((eShopLab.Models.Product)ViewBag.product).Prices.Max(d => d.PriceDate)).First().PriceValue)</h3>
            <div class="input-qty-detail">
                <input type="text" class="form-control input-qty text-center" value="1" ng-init="setSize(@ViewBag.SizeCategoryJson)">

                <select class="size-select" name="SizeCategory" ng-model="sizeScope.choice" ng-options="size for size in sizeScope.SizeCategoryList"></select>
                <button id="addToCart" class="btn btn-primary"
                        ng-click="addItem(@ViewBag.product.ProductID, '@ViewBag.product.ProductName', '@String.Format("{0:0.00}", ((eShopLab.Models.Product)ViewBag.product).Prices.Where(p => p.PriceDate == ((eShopLab.Models.Product)ViewBag.product).Prices.Max(d => d.PriceDate)).First().PriceValue)' )"
                        onclick="toastr.success('You just added article in your shopping cart !')">
                    Add to Cart
                </button>
            </div>
            <br />
            <hr />
            <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
                <a class="addthis_button_preferred_1"></a>
                <a class="addthis_button_preferred_2"></a>
                <a class="addthis_button_preferred_3"></a>
                <a class="addthis_button_preferred_4"></a>
                <a class="addthis_button_compact"></a>
            </div>
            <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-4f0c254f1302adf8"></script>
        </div>
        <div class="clearfix"></div>
        <div class="col-lg-12 col-sm-12">
            <span class="title">RELATED PRODUCTS</span>
        </div>
        <div class="col-lg-4 col-sm-4 hero-feature text-center">
            <div class="thumbnail">
                <a href="detail.html" class="link-p">
                    <img src="~/images/product-10.jpg" alt="">
                </a>
                <div class="caption prod-caption">
                    <h4><a href="detail.html">Adidas Men Blue &amp; Red Striped Polo T-shirt </a></h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
                    <p>
                        <div class="btn-group">
                            <a href="#" class="btn btn-default">$ 22.22</a>
                            <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                        </div>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-4 hero-feature text-center">
            <div class="thumbnail">
                <a href="detail.html" class="link-p">
                    <img src="~/images/product-11.jpg" alt="">
                </a>
                <div class="caption prod-caption">
                    <h4><a href="detail.html">Adidas Men Flame Black T-shirt</a></h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
                    <p>
                        <div class="btn-group">
                            <a href="#" class="btn btn-default">$ 15.47</a>
                            <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                        </div>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-4 hero-feature text-center">
            <div class="thumbnail">
                <a href="detail.html" class="link-p">
                    <img src="~/images/product-12.jpg" alt="">
                </a>
                <div class="caption prod-caption">
                    <h4><a href="detail.html">Adidas Men Red Printed T-shirt</a></h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
                    <p>
                        <div class="btn-group">
                            <a href="#" class="btn btn-default">$ 20.63</a>
                            <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- End Product Detail -->
</div>

eShopLab/Views/Catlg/Index.cshtml
@model PagedList.IPagedList<eShopLab.Models.Product>
@using PagedList.Mvc;
@using eShopLab.Helper;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <!-- Categories -->
    <div class="floatleft">
        <span class="title">CATEGORIES</span>
        <div class="vignette">
            <div class="list-group list-categ">
                @foreach (var cat in ViewBag.Categories)
                {
                    if (cat.CategoryID == ViewBag.categoryID)
                    {
                        @Html.ActionLink((string)cat.CategoryName, "Index", new { categoryID = cat.CategoryID }, new { @class = "list-group-item active" });
                    }
                    else
                    {
                        @Html.ActionLink((string)cat.CategoryName, "Index", new { categoryID = cat.CategoryID }, new { @class = "list-group-item" });
                    }
                }
            </div>
        </div>
        <select class="sort-select" onchange="location = this.options[this.selectedIndex].value;">
            <option value="@Url.Action("Index", "Catlg", new { categoryID = ViewBag.categoryID, sortOrder = "", currentFilter = ViewBag.CurrentFilter })"></option>
            <option @if (ViewBag.CurrentSort == "Name_desc") { <text> selected </text>  } value="@Url.Action("Index", "Catlg", new { categoryID = ViewBag.categoryID, sortOrder = "Name_desc", currentFilter = ViewBag.CurrentFilter })">Descending name</option>
            <option @if (ViewBag.CurrentSort == "Price_asc") { <text> selected </text>  } value="@Url.Action("Index", "Catlg", new { categoryID = ViewBag.categoryID, sortOrder = "Price_asc", currentFilter = ViewBag.CurrentFilter })">Ascending price</option>
            <option @if (ViewBag.CurrentSort == "Price_desc") { <text> selected </text>  } value="@Url.Action("Index", "Catlg", new { categoryID = ViewBag.categoryID, sortOrder = "Price_desc", currentFilter = ViewBag.CurrentFilter })">Descending price</option>
        </select>
    </div>
    <!-- End Categories -->
    <!-- Catalogue -->
    @if (Model != null)
    {
        <div class="floatleft">
            <span class="title">PRODUCTS CATALOGUE</span>

            <div class="vignette hero-feature text-center">
                <div class="thumbnail">
                    @Html.ActionImageCatlg("Details", "Catlg", Model.First().ProductID, Model.First().Media.First().MediaUrl, "")
                    <div class="caption prod-caption">
                        <h4><a href="detail.html">@Model.First().ProductName</a></h4>
                        <p>@Model.First().ProductDescription</p>
                        <p>
                            <div class="btn-group">
                                <a href="#" class="btn btn-default">@String.Format("{0:C}", Model.First().Prices.Where(p => p.PriceDate == Model.First().Prices.Max(d => d.PriceDate)).First().PriceValue)</a>
                                <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                            </div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="ajusting"></div>
        bool first = true;
        foreach (var product in Model)
        {
            if (!first)
            {
                <div class="vignette hero-feature text-center">
                    <div class="thumbnail">
                        @Html.ActionImageCatlg("Details", "Catlg", product.ProductID, product.Media.First().MediaUrl, "")
                        <div class="caption prod-caption">
                            <h4><a href="detail.html">@product.ProductName</a></h4>
                            <p>@product.ProductDescription</p>
                            <p>
                                <div class="btn-group">
                                    <a href="#" class="btn btn-default">@String.Format("{0:C}", product.Prices.Where(p => p.PriceDate == product.Prices.Max(d => d.PriceDate)).First().PriceValue)</a>
                                    <a href="@Url.Action("Details", "Catlg", new { id = product.ProductID })" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
            }
            first = false;
        }

        <div class="clearfix"></div>

        <div class="text-center">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, categoryID = ViewBag.categoryID, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
    <!-- End Catalogue -->
    }
    <br />
</div>

<a href="#top" class="back-top text-center" onclick="$('body,html').animate({scrollTop:0},500); return false">
    <i class="fa fa-angle-double-up"></i>
</a>